/*
 * API de servers
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class DefaultApiController : Controller
    { 
        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="name"></param>
        /// <response code="200">retorna 200</response>
        [HttpDelete]
        [Route("//servers")]
        [ValidateModelState]
        [SwaggerOperation("ServersDelete")]
        public virtual IActionResult ServersDelete([FromRoute][Required]string name)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        
        /// <response code="200">retorna lista de servers</response>
        [HttpGet]
        [Route("//servers")]
        [ValidateModelState]
        [SwaggerOperation("ServersGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Server), description: "retorna lista de servers")]
        public virtual IActionResult ServersGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Server));

            string exampleJson = null;
            exampleJson = "{\n  \"endpoints\" : {\n    \"minecraft\" : \"minecraft\",\n    \"rcon\" : \"rcon\"\n  },\n  \"name\" : \"name\"\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Server>(exampleJson)
            : default(Server);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="name"></param>
        /// <response code="201">retorna 201 (created)</response>
        [HttpPost]
        [Route("//servers")]
        [ValidateModelState]
        [SwaggerOperation("ServersPost")]
        public virtual IActionResult ServersPost([FromBody]string name)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);


            throw new NotImplementedException();
        }
    }
}
